function makeBlankCharacter(): CharacterInput {
  return {
    id: uuid(),
    meta: {
      name: "",
      playerName: "",
      ancestry: "Human (Roshar)",
      path: "Windrunner",
      level: 1,
      tier: 1,
    },
    attributes: {
      awareness: 0,
      intellect: 0,
      presence: 0,
      speed: 0,
      strength: 0,
      willpower: 0,
    },
    health: {
      current: 10,
      total: 10,
      bonus: 0,
      wounds: 0,
    },
    focus: {
      current: 0,
      total: 2,
      bonus: 0,
    },
    investiture: {
      current: 0,
      total: 0,
    },
    deflect: 0,
    movement: 20,
    movementBonus: 0,
    recoveryDie: "d4",
    sensesRange: "",
    liftingCapacity: undefined,
    expertise: [],
    talents: [],
    weapons: [
      {
        name: "Unarmed Attack",
        skill: "Athletics",
        damageDice: "d1",
        damageType: "impact",
        traits: "Unique",
        expertTraits: "Momentum, Offhand",
        handling: 0,
        carried: 2,
        ammo: 0,
        maxAmmo: 0,
        type: 0,
      },
    ],
    conditionsText: "",
    skills: DEFAULT_SKILLS.map((skill) => ({ ...skill })),
    notes: "",
    version: "1.0.0",
  };
}
