import type { CharacterInput } from "./character.schema";

export type WeaponTemplate = {
  skill: CharacterInput["weapons"][number]["skill"];
  damageDice: string;
  damageType: string;
  traits: string;
  expertTraits: string;
  carried: number;
  ammo: number;
  maxAmmo: number;
  type: number;
};

export const WEAPON_OPTIONS = [
  "Axe",
  "Crossbow",
  "Grandbow",
  "Greatsword",
  "Half-Shard",
  "Hammer",
  "Javelin",
  "Knife",
  "Longbow",
  "Longspear",
  "Longsword",
  "Mace",
  "Painrial (amplifying)",
  "Poleaxe",
  "Rapier",
  "Shardblade",
  "Shardblade (Radiant)",
  "Shield",
  "Shortbow",
  "Shortspear",
  "Sidesword",
  "Sling",
  "Staff",
  "Warhammer",
] as const;

export const WEAPON_TEMPLATES: Record<string, WeaponTemplate> = {
  Axe: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Crossbow: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Grandbow: {
    skill: "Heavy Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Greatsword: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  "Half-Shard": {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Hammer: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Javelin: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Knife: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Longbow: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Longspear: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Longsword: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Mace: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  "Painrial (amplifying)": {
    skill: "Lore",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Poleaxe: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Rapier: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Shardblade: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  "Shardblade (Radiant)": {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Shield: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Shortbow: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Shortspear: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Sidesword: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Sling: {
    skill: "Light Weaponry",
    damageDice: "d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Staff: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
  Warhammer: {
    skill: "Athletics",
    damageDice: "d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
  },
};
