import type { CharacterInput } from "./character.schema";

export type WeaponTemplate = {
  skill: CharacterInput["weapons"][number]["skill"];
  damageDice: string;
  damageType: string;
  traits: string;
  expertTraits: string;
  carried: number;
  ammo: number;
  maxAmmo: number;
  type: number;
  range: string;
  subtype: string;
};

export const WEAPON_OPTIONS = [
  "Axe",
  "Crossbow",
  "Grandbow",
  "Greatsword",
  "Half-Shard",
  "Hammer",
  "Javelin",
  "Knife",
  "Longbow",
  "Longspear",
  "Longsword",
  "Mace",
  "Painrial (amplifying)",
  "Poleaxe",
  "Rapier",
  "Shardblade",
  "Shardblade (Radiant)",
  "Shield",
  "Shortbow",
  "Shortspear",
  "Sidesword",
  "Sling",
  "Staff",
  "Warhammer",
] as const;

export const WEAPON_TEMPLATES: Record<string, WeaponTemplate> = {
  Axe: {
    skill: "Heavy Weaponry",
    damageDice: "1d6",
    damageType: "keen",
    traits: "Thrown[20/60]",
    expertTraits: "Offhand",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Crossbow: {
    skill: "Heavy Weaponry",
    damageDice: "1d8",
    damageType: "keen",
    traits: "Loaded[1], Two-Handed",
    expertTraits: "Deadly",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Ranged [100/400]",
    subtype: "",
  },
  Grandbow: {
    skill: "Heavy Weaponry",
    damageDice: "2d6",
    damageType: "keen",
    traits: "Cumbersone [5], Two-Handed",
    expertTraits: "Pierce",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Ranged [150/600]",
    subtype: "",
  },
  Greatsword: {
    skill: "Heavy Weaponry",
    damageDice: "1d10",
    damageType: "keen",
    traits: "Two-Handed",
    expertTraits: "Deadly",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  "Half-Shard": {
    skill: "Heavy Weaponry",
    damageDice: "2d4",
    damageType: "impact",
    traits: "Defensive, Two-Handed, Unique",
    expertTraits: "Momentum",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Hammer: {
    skill: "Heavy Weaponry",
    damageDice: "1d10",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "Momentum",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Javelin: {
    skill: "Light Weaponry",
    damageDice: "1d6",
    damageType: "keen",
    traits: "Thrown[30/1200]",
    expertTraits: "Indirect",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Knife: {
    skill: "Light Weaponry",
    damageDice: "1d4",
    damageType: "keen",
    traits: "Discreet",
    expertTraits: "Offhand, Thrown[20/60]",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Longbow: {
    skill: "Heavy Weaponry",
    damageDice: "1d6",
    damageType: "keen",
    traits: "Two-Handed",
    expertTraits: "Indirect",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Ranged [150/600]",
    subtype: "",
  },
  Longspear: {
    skill: "Heavy Weaponry",
    damageDice: "1d8",
    damageType: "keen",
    traits: "Two-Handed",
    expertTraits: "Defensive",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee +5",
    subtype: "",
  },
  Longsword: {
    skill: "Heavy Weaponry",
    damageDice: "1d8",
    damageType: "keen",
    traits: "Quickdraw, Two-Handed",
    expertTraits: "Unique: loses Two-Handed trait",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Mace: {
    skill: "Light Weaponry",
    damageDice: "1d6",
    damageType: "impact",
    traits: "",
    expertTraits: "Momentum",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  "Painrial (amplifying)": {
    skill: "Light Weaponry",
    damageDice: "1d6",
    damageType: "vital damage",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "invested",
  },
  Poleaxe: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Rapier: {
    skill: "Light Weaponry",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Shardblade: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  "Shardblade (Radiant)": {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Shield: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Shortbow: {
    skill: "Light Weaponry",
    damageDice: "1d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Ranged [80/320]",
    subtype: "",
  },
  Shortspear: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Sidesword: {
    skill: "Light Weaponry",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Sling: {
    skill: "Light Weaponry",
    damageDice: "1d1",
    damageType: "impact",
    traits: "",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Ranged [30/120]",
    subtype: "",
  },
  Staff: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
  Warhammer: {
    skill: "Athletics",
    damageDice: "1d1",
    damageType: "impact",
    traits: "Two-Handed",
    expertTraits: "",
    carried: 2,
    ammo: 0,
    maxAmmo: 0,
    type: 0,
    range: "Melee",
    subtype: "",
  },
};
